site:
  title: Elemental documentation
  url: /
  start_page: elemental-product-docs::index.adoc

content:
  sources:
    - url: ./
      branches: [main]

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./susecom-2023

asciidoc:
  extensions:
    - asciidoctor-kroki
