site:
  title: Elemental documentation
  url: /
  start_page: elemental-product-docs::index.adoc

content:
  sources:
    - url: ./
      branches: [main, 1.5]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
